### ISSUE TITLE
Обработка исключений

### ISSUE THREAD

**Issue by liberaid2** [ilya-nozhkin/embox#24]
Частично реализована

Ветка: `xtensa-esp8266-exceptions`
Вики о том, как парсить исключения: [тык](https://github.com/ilya-nozhkin/embox/wiki/%D0%9F%D0%B0%D1%80%D1%81%D0%B8%D0%BD%D0%B3-%D0%B8%D1%81%D0%BA%D0%BB%D1%8E%D1%87%D0%B5%D0%BD%D0%B8%D0%B9)

**Comment by ReDFoX43rus** [comment]
Вики о том, как обрабатывать исключения: [тык](https://github.com/ilya-nozhkin/embox/wiki/%D0%9F%D0%B0%D1%80%D1%81%D0%B8%D0%BD%D0%B3-%D0%B8%D1%81%D0%BA%D0%BB%D1%8E%D1%87%D0%B5%D0%BD%D0%B8%D0%B9)

**Comment by ilya-nozhkin** [comment]
Реализовал частичную поддержку исключений (старый вариант выпилил). Теперь выдается только текущий контекст, а именно регистры: ar0-15, ps, sar, epc1-3, depc и exccause (подробности, что это такое, спрашивать у меня или читать Xtensa Instuction Set Architecture). При этом на каждый тип исключения можно добавить свой обработчик, который будет говорить что-то полезное (Там в файле /arch/xtensa/kernel/exceptions.c есть спец. массив), но на данный момент я сделал только общий обработчик и обработчик Level 1 interrupt, кому интересно, можете заняться остальным.
